// <auto-generated />
using System;
using MentalHealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentalHealthApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentalHealth.Data.Models.Cilj", b =>
                {
                    b.Property<int>("CiljId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiljId"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazivCilja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcenatNapretka")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CiljId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Ciljevi");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.DnevnikMisli", b =>
                {
                    b.Property<int>("BeleskaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BeleskaId"));

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deljena")
                        .HasColumnType("boolean");

                    b.Property<string>("DeljenjeTerapeutId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BeleskaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("DnevnikMisli");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.DnevnoRaspolozenje", b =>
                {
                    b.Property<int>("RaspolozenjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaspolozenjeId"));

                    b.Property<string>("Afirmacija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emotikon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KvalitetIshrane")
                        .HasColumnType("integer");

                    b.Property<int>("KvalitetSna")
                        .HasColumnType("integer");

                    b.Property<int>("NivoFizickeAktivnosti")
                        .HasColumnType("integer");

                    b.Property<int>("OcenaRaspolozenja")
                        .HasColumnType("integer");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UzrociStresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RaspolozenjeId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("DnevnaRaspolozenja");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.EdukativniSadrzaj", b =>
                {
                    b.Property<int>("SadrzajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SadrzajId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SadrzajId");

                    b.ToTable("EdukativniSadrzaj");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.KorakCilja", b =>
                {
                    b.Property<int>("KorakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KorakId"));

                    b.Property<int>("CiljId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpisKoraka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Zavrsen")
                        .HasColumnType("boolean");

                    b.HasKey("KorakId");

                    b.HasIndex("CiljId");

                    b.ToTable("KoraciCiljeva");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.KorisnickiProfil", b =>
                {
                    b.Property<int>("ProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilId"));

                    b.Property<string>("Cilj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpisProfila")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferiraniSat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrimiMotivacionuPoruku")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrimiPodsetnik")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilnaSlika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProfilId");

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.ToTable("KorisnickiProfili");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Korisnik", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AktivnaNalog")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnonimnaRegistracija")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ZadnjaAktivnost")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Navika", b =>
                {
                    b.Property<int>("NavikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NavikaId"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazivNavike")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ucestalost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NavikaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Navike");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Podsetnik", b =>
                {
                    b.Property<int>("PodsetnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PodsetnikId"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VremePodsetnika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PodsetnikId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Podsetnici");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Poruka", b =>
                {
                    b.Property<int>("PorukaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PorukaId"));

                    b.Property<DateTime?>("DatumCitanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PosiljaocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimalacId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Procitana")
                        .HasColumnType("boolean");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SadrzajSifrovane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SesijaId")
                        .HasColumnType("integer");

                    b.HasKey("PorukaId");

                    b.HasIndex("PosiljaocId");

                    b.HasIndex("PrimalacId");

                    b.HasIndex("SesijaId");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.PracenjeNavike", b =>
                {
                    b.Property<int>("PracenjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PracenjeId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NavikaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Zavrseno")
                        .HasColumnType("boolean");

                    b.HasKey("PracenjeId");

                    b.HasIndex("NavikaId");

                    b.ToTable("PracenjaNavika");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ocena")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.SOSKontakt", b =>
                {
                    b.Property<int>("SOSKontaktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SOSKontaktId"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImeKontakta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SOSKontaktId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("SOSKontakti");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Sesija", b =>
                {
                    b.Property<int>("SesijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SesijaId"));

                    b.Property<string>("BeleskeTerapeuta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumSesije")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackKlijenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KlijentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerapeutId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrajanjeSesijeMinuta")
                        .HasColumnType("integer");

                    b.HasKey("SesijaId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("TerapeutId");

                    b.ToTable("Sesije");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Terapeut", b =>
                {
                    b.Property<int>("TerapeutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TerapeutId"));

                    b.Property<int>("BrojRecenzija")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Dostupan")
                        .HasColumnType("boolean");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Licenca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpisPrakse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProsecnaOcena")
                        .HasColumnType("double precision");

                    b.Property<decimal>("SatnicaKonzultacije")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Zvanje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TerapeutId");

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.ToTable("Terapeuti");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.ZakazivanjeSesije", b =>
                {
                    b.Property<int>("ZakazivanjeSesijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZakazivanjeSesijeId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumZakazane")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KlijentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TerapeutId")
                        .HasColumnType("integer");

                    b.HasKey("ZakazivanjeSesijeId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("TerapeutId");

                    b.ToTable("ZakazivanjaSesija");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Terapeut",
                            NormalizedName = "TERAPEUT"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Klijent",
                            NormalizedName = "KLIJENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Cilj", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Ciljevi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.DnevnikMisli", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("DnevnikMisli")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.DnevnoRaspolozenje", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Raspolozenja")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.KorakCilja", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Cilj", "Cilj")
                        .WithMany("Koraci")
                        .HasForeignKey("CiljId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cilj");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.KorisnickiProfil", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithOne("Profil")
                        .HasForeignKey("MentalHealth.Data.Models.KorisnickiProfil", "KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Navika", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Navike")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Podsetnik", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Podsetnici")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Poruka", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Posiljaoc")
                        .WithMany("PoslatePoruke")
                        .HasForeignKey("PosiljaocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Primalac")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("PrimalacId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MentalHealth.Data.Models.Sesija", "Sesija")
                        .WithMany("Poruke")
                        .HasForeignKey("SesijaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Posiljaoc");

                    b.Navigation("Primalac");

                    b.Navigation("Sesija");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.PracenjeNavike", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Navika", "Navika")
                        .WithMany("Pracenja")
                        .HasForeignKey("NavikaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Navika");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Recenzija", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.SOSKontakt", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithMany("SOSKontakti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Sesija", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Klijent")
                        .WithMany("SesijeKaoKlijent")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Terapeut")
                        .WithMany("SesijeKaoTerapeut")
                        .HasForeignKey("TerapeutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Terapeut");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Terapeut", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Korisnik")
                        .WithOne("Terapeut")
                        .HasForeignKey("MentalHealth.Data.Models.Terapeut", "KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.ZakazivanjeSesije", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MentalHealth.Data.Models.Terapeut", "Terapeut")
                        .WithMany("ZakazaneSesije")
                        .HasForeignKey("TerapeutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Terapeut");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealth.Data.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MentalHealth.Data.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Cilj", b =>
                {
                    b.Navigation("Koraci");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Korisnik", b =>
                {
                    b.Navigation("Ciljevi");

                    b.Navigation("DnevnikMisli");

                    b.Navigation("Navike");

                    b.Navigation("Podsetnici");

                    b.Navigation("PoslatePoruke");

                    b.Navigation("PrimljenePoruke");

                    b.Navigation("Profil")
                        .IsRequired();

                    b.Navigation("Raspolozenja");

                    b.Navigation("Recenzije");

                    b.Navigation("SOSKontakti");

                    b.Navigation("SesijeKaoKlijent");

                    b.Navigation("SesijeKaoTerapeut");

                    b.Navigation("Terapeut")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Navika", b =>
                {
                    b.Navigation("Pracenja");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Sesija", b =>
                {
                    b.Navigation("Poruke");
                });

            modelBuilder.Entity("MentalHealth.Data.Models.Terapeut", b =>
                {
                    b.Navigation("ZakazaneSesije");
                });
#pragma warning restore 612, 618
        }
    }
}
